echo '' > /root/ArmsCommander/PROJECT_HELLS_HORSES/convert_wordlist.txt
echo '' > /root/ArmsCommander/recon/MT_Recon_Wordlist
echo '' > /root/ArmsCommander/Pentesting_Offensive_Security_Scripts/nmap_wl_scan_wordlist
echo '' > /root/ArmsCommander/recon/CornHarvester_Wordlist
echo '' > /root/ArmsCommander/Pentesting_Offensive_Security_Scripts/mx_info_gatherer_wordlist
echo '' > /root/ArmsCommander/recon/CornHarvester_Wordlist.txt
echo '' > /root/ArmsCommander/recon/CornHarvester_Wordlist_fixed.txt
echo '' > /root/ArmsCommander/recon/CornHarvester_Wordlist_fixed.txt_fixed.txt
echo '' > /root/ArmsCommander/passwordattacks/CocaineFactory/wordlist
echo '' > /root/ArmsCommander/passwordattacks/CUDA_Setup_Utility/wordlist
echo '' > /root/ArmsCommander/passwordattacks/MeowMix/wordlist
echo '' > /root/ArmsCommander/passwordattacks/Pyrit/wordlist
echo '' > /root/ArmsCommander/passwordattacks/Pyrit/read_wordlist.py
echo '' > /root/ArmsCommander/recon/recon/CornHarvester_Wordlist